[build]
  # Directory where the build system installs dependencies
  # and runs your build. Store your package.json, .nvmrc, etc here.
  # If not set, defaults to the root directory.

  # the docs say this is relative to the base directory, but this doesn't seem accurate
  publish = "dist"

  command = "pnpm build --verbose"

  environment = { NODE_VERSION = "22" }